on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
  
jobs:
    get-next-version:
      uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@v4
  
    build:
      name: Build
      runs-on: ubuntu-latest
      needs:
        - get-next-version
  
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Install Rust toolchain
          uses: dtolnay/rust-toolchain@master
          with:
            toolchain: stable
  
        - name: Rust Cache
          uses: Swatinem/rust-cache@v2
  
        - name: Run Tests
          run: cargo test
          env:
            FLUXPOINT_API_TOKEN: ${{ secrets.FLUXPOINT_API_TOKEN }}  

        - name: Cargo build
          run: cargo build --release

        - name: Cargo publish
          run: cargo publish --token ${{ secrets.CRATESIO_TOKEN }}
          if: github.event_name != 'pull_request'